### PR TITLE
Make Array.Extra.map3-5 faster

### PR DESCRIPTION
**Pull request by miniBill**

### CODE REVIEW

**Comment by gampleman** [comment]
Do we have a benchmark? (In this case I'm not really doubting that this will be at the very least about the same with some improvement to readability, but hey).

**Review by gampleman — APPROVED** [review]

**Comment by miniBill** [comment]
No, I haven't benchmarked it, but I can!

**Comment by miniBill** [comment]
image
Eh, I expected a bigger difference

**Comment by miniBill** [comment]
image

**Comment by gampleman** [comment]
So slight improvement, but not really a game changer. I think that's fair and I personally like this implementation a bit more, so happy to merge.

**Pull request merged**
